#!/bin/sh
# Must have hbase/bin in path.

# Create test table
echo "create 'test','d'" | hbase shell

# Put test data
echo "put 'test', '1', 'd:data', 'HelloWorld!'
put 'test', '2', 'd:data', 'HelloWorld!'
put 'test', '3', 'd:data', 'HelloWorld!'
put 'test', '4', 'd:data', 'HelloWorld!'
put 'test', '5', 'd:data', 'HelloWorld!'
put 'test', '6', 'd:data', 'HelloWorld!'
put 'test', '7', 'd:data', 'HelloWorld!'
put 'test', '8', 'd:data', 'HelloWorld!'
put 'test', '9', 'd:data', 'HelloWorld!'
put 'test', '10', 'd:data', 'HelloWorld!'
put 'test', '11', 'd:data', 'HelloWorld!'
put 'test', '12', 'd:data', 'HelloWorld!'
put 'test', '13', 'd:data', 'HelloWorld!'
put 'test', '14', 'd:data', 'HelloWorld!'
put 'test', '15', 'd:data', 'HelloWorld!'
put 'test', '16', 'd:data', 'HelloWorld!'
put 'test', '17', 'd:data', 'HelloWorld!'
put 'test', '18', 'd:data', 'HelloWorld!'
put 'test', '19', 'd:data', 'HelloWorld!'
put 'test', '20', 'd:data', 'HelloWorld!'
put 'test', '21', 'd:data', 'HelloWorld!'
put 'test', '22', 'd:data', 'HelloWorld!'
put 'test', '23', 'd:data', 'HelloWorld!'
put 'test', '24', 'd:data', 'HelloWorld!'
put 'test', '25', 'd:data', 'HelloWorld!'
put 'test', '26', 'd:data', 'HelloWorld!'
put 'test', '27', 'd:data', 'HelloWorld!'
put 'test', '28', 'd:data', 'HelloWorld!'
put 'test', '29', 'd:data', 'HelloWorld!'
put 'test', '30', 'd:data', 'HelloWorld!'
put 'test', '31', 'd:data', 'HelloWorld!'
put 'test', '32', 'd:data', 'HelloWorld!'
put 'test', '33', 'd:data', 'HelloWorld!'
put 'test', '34', 'd:data', 'HelloWorld!'
put 'test', '35', 'd:data', 'HelloWorld!'
put 'test', '36', 'd:data', 'HelloWorld!'
put 'test', '37', 'd:data', 'HelloWorld!'
put 'test', '38', 'd:data', 'HelloWorld!'
put 'test', '39', 'd:data', 'HelloWorld!'
put 'test', '40', 'd:data', 'HelloWorld!'
put 'test', '41', 'd:data', 'HelloWorld!'
put 'test', '42', 'd:data', 'HelloWorld!'
put 'test', '43', 'd:data', 'HelloWorld!'
put 'test', '44', 'd:data', 'HelloWorld!'
put 'test', '45', 'd:data', 'HelloWorld!'
put 'test', '46', 'd:data', 'HelloWorld!'
put 'test', '47', 'd:data', 'HelloWorld!'
put 'test', '48', 'd:data', 'HelloWorld!'
put 'test', '49', 'd:data', 'HelloWorld!'
put 'test', '50', 'd:data', 'HelloWorld!'" | hbase shell

